spring.application.name=practice

spring.datasource.url=jdbc:oracle:thin:@//192.168.219.101:1521/XEPDB1
spring.datasource.username=practice
spring.datasource.password=rhddb1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false